#!/bin/bash 

nextflow run main.nf \
  -resume \
  -profile local,singularity \
  --fastq_dir ../../read_preprocessing/trimmed_fastq/ \
  --fastq_pattern "F[23]*_[12].fastq.gz" \
  --genome_fasta refseq/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.gz \
  --subsample_size 100000 
